const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  ACCOUNTANT: 'accountant',
  STUDENT: 'student',
};

const PERMISSIONS = {
  // Feature: [roles allowed]
  ADMIN_MANAGEMENT: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  ACCOUNTANT_MANAGEMENT: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  STUDENT_MANAGEMENT: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  COURSE_MANAGEMENT: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  SEMESTER_UPGRADE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  FEE_TEMPLATE_MANAGEMENT: [ROLES.SUPER_ADMIN],
  FEE_ASSIGNMENT: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  CHARGES_MANAGEMENT: [ROLES.SUPER_ADMIN],
  SERVICE_MANAGEMENT: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  OFFLINE_FEE_ENTRY: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT],
  SEND_NOTIFICATIONS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT],
  PAYMENT_HISTORY: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  ADVANCE_REFUND: [ROLES.SUPER_ADMIN],
  AUDIT_LOGS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  REPORTS_ANALYTICS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT],
  SYSTEM_SETTINGS: [ROLES.SUPER_ADMIN],
  RECEIPT_GENERATION: [ROLES.ACCOUNTANT, ROLES.STUDENT],
  PROFILE_SETTINGS: [ROLES.ACCOUNTANT, ROLES.STUDENT],
  VIEW_FEE_DETAILS: [ROLES.STUDENT],
  PAY_ONLINE: [ROLES.STUDENT],
  DOWNLOAD_RECEIPTS: [ROLES.STUDENT],
  VIEW_SERVICES: [ROLES.STUDENT, ROLES.ACCOUNTANT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
  PROFILE_UPDATE: [ROLES.STUDENT],
  SEMESTER_INFO_VIEW: [ROLES.STUDENT],
  
  // Dynamic Fee Management System
  FEE_MANAGEMENT: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  FEE_PAYMENT: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT],
  FEE_CATEGORY_MANAGEMENT: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  FEE_TEMPLATE_CREATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  STUDENT_FEE_GENERATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  STUDENT_FEE_MODIFY: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  FINE_MANAGEMENT: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  DISCOUNT_MANAGEMENT: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  PAYMENT_RECORD: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT],
  PAYMENT_VERIFY: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  PAYMENT_REFUND: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  
  // Semester Upgrade System
  SEMESTER_UPGRADE_VIEW: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT],
  SEMESTER_ROLLBACK: [ROLES.SUPER_ADMIN],
  BULK_SEMESTER_UPGRADE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  MANUAL_SEMESTER_UPGRADE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  
  // Service Management System
  MANAGE_SERVICES: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT],
  BULK_SERVICE_UPDATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  HOSTEL_MANAGEMENT: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  MESS_MANAGEMENT: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  TRANSPORT_MANAGEMENT: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  LIBRARY_MANAGEMENT: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  SERVICE_STATISTICS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT],
};

module.exports = { ROLES, PERMISSIONS };

